---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cephfs-claim1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
